services:
  postgres:
    image: postgres:17.5
    restart: unless-stopped
    container_name: hono-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=rahul
      - POSTGRES_DB=todos